alter table unidade_tipo_avaliacao_licenca drop constraint if exists UKcdje95t2heav6arkqvwwjxm5c;
alter table unidade_tipo_avaliacao_licenca add constraint UKcdje95t2heav6arkqvwwjxm5c unique (unidade_tipo_avaliacao_id, licenca_id, ordem);
