#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:

  # REDIS REPOSITORY
  data:
    redis:
      repositories:
        enabled: false

  #JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

#LOGGING
logging:
  level:
    root: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.web.client: WARN
    org.springframework.context.support: WARN
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
  file: /var/log/${spring.application.name}.log

# configuracoes do actuator
management:
  endpoint:
    logfile:
      external-file: /var/log/${spring.application.name}.log
