#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:
  application.name: Assessment Online
  jmx.enabled: false

#DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://localhost:5432/assessment
    username: assessment
    password: assessment

#JPA
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
    show-sql: true
    format_sql: true
    open-in-view: false
    properties:
      hibernate.dialect: br.com.assessment.infrastructure.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.default_schema: public
      org.hibernate.envers.audit_table_suffix: _aud
      org.hibernate.envers.revision_field_name: rev
      org.hibernate.envers.revision_type_field_name: revtype
      org.hibernate.envers.default_schema: public

#FLYWAY
  flyway:
    check-location: false
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: v


#LOGGING
logging.level:
  org.hibernate: INFO
  org.directwebremoting: INFO
  org.springframework.web: INFO
  org.springframework.context.support: INFO
  org.springframework.security: INFO

#WEB CONTAINER
server:
  servlet:
    context-path:
    session:
      persistent: true
  compression.enabled: true
