#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:

#JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

#LOGGING
logging.level:
  org.hibernate: INFO
  org.springframework.web: INFO
  org.springframework.context.support: INFO
  org.springframework.security: INFO
