#Configuração destinada ao ambiente de desenvolvimento, os demais perfis hedarão deste
spring:
  application.name: Assessment Online
  jmx.enabled: false

#DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://127.0.0.1:5432/assessment
    username: assessment
    password: assessment

#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: br.com.assessment.infrastructure.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.default_schema: public
#      hibernate.multiTenancy: SCHEMA
#      hibernate.tenant_identifier_resolver: br.com.assessment.application.multitenancy.TenantIdentifierResolver
#      hibernate.multi_tenant_connection_provider: br.com.assessment.application.multitenancy.MultiTenantConnectionProviderImpl
      org.hibernate.envers.audit_table_suffix: _audited
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type
      org.hibernate.envers.default_schema: auditing

#THYMELEAF
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/META-INF/resources/
    suffix: .html

#STATIC RESOURCES
  resources.static-locations: classpath:/META-INF/resources/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**

#FLYWAY
  flyway:
    enabled: true
    check-location: true
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: v

  webflux:
    static-path-pattern: /resources/**


#LOGGING
logging.level:
  org.hibernate: INFO
  org.directwebremoting: INFO
  org.springframework.web: INFO
  org.springframework.context.support: INFO
  org.springframework.security: INFO

